---
title: "Study Design"
author: "John Woolley"
date: "10/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Model response data

```{r cars}

respondents <- (1:180)
grp_size <- length(respondents)/3
treat_groups <- c(rep(1,grp_size),rep(2,grp_size),rep(3,grp_size))
lifetime_trades <- rlnorm(length(respondents), meanlog=log(50), sdlog=log(5))
lifetime_trades <- as.integer(lifetime_trades)
treatments$trade_block <- 
preference <- sample(c('value','growth'),length(respondents),replace=TRUE)
assignment <- data.frame(respondents=respondents, treat_group=treat_groups, trades=lifetime_trades, preference=preference)

rand_treatment <- sample(nrow(assignment))
assignment$treat_group <- assignment$treat_group[rand_treatment]
assignment$variance <- 10
assignment$mean <- 100
assignment$skewness <- 0
assignment$skewness[assignment$treat_group==2] = 0.5
assignment$skewness[assignment$treat_group==3] = -0.5
assignment$risk_premium <- exp(log(0.07) + log(assignment$variance) * -0.2 + assignment$skewness * -1 + assignment$skewness * log(assignment$variance) * -0.1 + rnorm(nrow(assignment),0,1)) 
assignment$response = assignment$mean/(1+assignment$risk_premium)
assignment
```

## Including Plots

Histograms

```{r pressure, echo=FALSE}
hist(assignment$response)
hist(assignment$response[assignment$treat_group==1])
hist(assignment$response[assignment$treat_group==2])
hist(assignment$response[assignment$treat_group==3])
```

```{r pressure, echo=FALSE}
hist(assignment$risk_premium)
hist(assignment$risk_premium[assignment$treat_group==1])
hist(assignment$risk_premium[assignment$treat_group==2])
hist(assignment$risk_premium[assignment$treat_group==3])
```